### ISSUE TITLE
link to doc doesn't show

### ISSUE THREAD

**Issue by morgash1989** [altamkp/godot-docs-vscode-csharp#1]
Hello and thank you for the plugin.

Contrary to the captured gif, I don't have the doc link at the bottom of the hover popup.

VSCode version 1.86.0

I don't know typescript enough to pinpoint the problem.
I disabled all non-dependencies plugins and it still doesn't show. So I don't think it's a conflict.

~I use **Godot .NET Tools** for the debugger and not **C# tools for Godot**. May be it come from that I haven't tested yet.~

edit:
Well I don't know what exactly happened, either Omnisharp had not started or the plugin need **C# Dev Kit** as a dependencies, or Installing it has reset some settings or other something... 

It works now.

**Comment by altamkp** [comment]
Thank you for your feedback.

I have tried to reproduce the problem by uninstalling the docs extension and the C# extension. When I install the docs extension, the C# extension is automatically installed together with it since it is marked as a dependency in `package.json`. Please check if you have the offical [C# extension] from Microsoft enabled should the docs extension failed to display the link.

I have also tried disabling/enabling the C# Dev Kit extension and, as expected, there was no effect to the docs extension.

Happy coding 🫡
